### ISSUE TITLE
Stopping rules assessed for specific dose and not just for the nextbest dose

### ISSUE THREAD

**Issue by dimitriskontosClinBAY** [Roche/crmPack#108]
To do:

- [x] See design doc https://github.com/Roche/crmPack/blob/main/design/stop-specific-dose.Rmd
- [x] Implement `v_stop_specific_dose()` validation function
- [x] Implement `StopSpecificDose` class
- [x] Implement `StopSpecificDose()` user constructor
- [x] Implement `stopTrial()` method for `StopSpecificDose`

Background: 

**Summary**

When defining a simulation design, we would like to have the option to  assess if Stopping rules are met for specific doses of the planned dose grid and not just for the nextBest dose.

For example assume we have a data set-up like below:

     Data(doseGrid = c(1.5, 2.5, 3.5, 4.5, 6, 7 ))

and that we want to implement a stopping rule as part of our dose escalation design simulations:
->Assuming a DLT rate of 30 %, we set=up our stopping rules to constantly check during each iteration, if the following conditions are met:

   stopping_rule_1 -> Minimum dose tested (1.5MBq) is toxic (DLT<=0.3) with probability T1 < 20%
   stopping_rule_2 -> Maximum possible dose (7.0MBq) is safe (DLT>0.3) with probability TN > 80% and 7.0MBq administered.

We could could rush and try set this up using stopping rules already available in the crmPACK for example and
only define a new class for stopping rule StoppingLowestDose. 
This could look like the below setting:

stopping_rule_1 <- StoppingLowestDose() & 
                                StoppingPatientsNearDose(nPatients=3, percentage=0) &
                                StoppingTargetProb(target=c(0.3, 1), prob=0.8)

stopping_rule_2 <- StoppingHighestDose() &
                               StoppingPatientsNearDose(nPatients=3,percentage=0) &
                               StoppingTargetProb(target=c(0, 0.3),prob=0.8)

But this would NOT really work correctly, because all the stopping rules during the design simulation process, 
are currently assessed at the nextbest dose  and not at a predefined dose of the planned dose grid.

A possible solution could be:
  1. An extension of the currently available stopping rules with an extra user input parameter(s) (slot(s)),
         where the dose of interest is defined OR else the default nextbest dose is used?
  2. An extension to the Design or Simulation object?
  3. Any other suggestion?

**Comment by danielinteractive** [comment]
from our initial brainstorming discussion:

A & B* | C
where B* defined as StopSpecificDose(B, dose = 1.5)

**Comment by danielinteractive** [comment]
have a look at https://github.com/Roche/crmPack/pull/125/files to see how to start the design doc
