### ISSUE TITLE
Clean-up `GeneralData` class

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#11]
To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] for classes: 
    - [x] test default constructor
    - [x] for reference classes: test methods
  - [x] for functions: as usual
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] keep externally used names so that we don't break downstream code
  - [x] consider renaming internal variables etc. if needed
  - [x] if a function is too long, break up into pieces
  - [x] for classes: move function definitions outside if possible (e.g. move validation function as `validityGeneralData()` to `DataClass-validity.R` and have corresponding test file `test-DataClass-validity.R`)
  - [x] in `setClass` function, just use the `slots` instead of outdated `representation`.

**Comment by wwojciech** [comment]
Hi Daniel ( @danielinteractive )


## History:
## 29/01/2014   file creation
## 07/02/2014   add cohort indices

**Comment by danielinteractive** [comment]
@wwojciech please remove that (I also added this to tasks boxes in the issue description now)

**Comment by wwojciech** [comment]
@danielinteractive, what do you think to name rename `Data-class.R` file to `GeneralData-class.R` (and similarly for the methods), since `GeneralData` is the most outer class for data-like objects? Then, I would use the same convention for  `GeneralDataClass-validity.R`, as this file would contain all the validity tests for all data-like object. For other (non-data) classes we could of course use the same strategy.

**Comment by wwojciech** [comment]
> @wwojciech please remove that (I also added this to tasks boxes in the issue description now)

I also removed `## Time-stamp: <[Data-class.R] by DSB Mon 11/05/2015 17:42>`

**Comment by wwojciech** [comment]
@danielinteractive , I also wanted to share/confirm one idea on how to implement validation functions. I see two approaches, based on:  `checkmate`/`assertthat` assertions or `Validate()` approach.

Using `checkmate`, `assertthat` assertions, without adding extra `Validate()` approach, is very clear, compact, easy to understand for code readers. But, in contrast to `Validate()` approach, it does not report cumulative error message, i.e. if the validation fails at the first assertion, then only the error corresponding to that assertion is returned and remaining assertions are not evaluated. `Validate()`, on the other hand, evaluates all the conditions, and reports cumulative error report (msg) at the end.

What do you think? Would you prefer to invoke `Validation()` in validation internal functions, or maybe we can use `checkmate`/`assertthat` assertions only?

Thanks!

**Comment by danielinteractive** [comment]
@wwojciech I would keep the name for `Data-class.R`

**Comment by danielinteractive** [comment]
@wwojciech there is an ongoing discussion at https://github.com/mllg/checkmate/issues/118 about making the `checkmate` package support validation functions. let's keep it simple for now - still use `Validation()` etc just use `checkmate` functions where possible, i.e. in normal functions for assertions, or the `test_*()` functions from it for validation purposes but then generating the message "manually". See `helios` for examples.

**Comment by wwojciech** [comment]
Understood - thanks a lot @danielinteractive !

**Comment by wwojciech** [comment]
If this is ok, for the point `Refactor as needed`, I would: `Data-validity.R` and corresponding test file `test-Data-validity.R`, which would be consistent with `helios` and I think looks clear.

**Comment by danielinteractive** [comment]
@wwojciech sounds good!
