### ISSUE TITLE
design how to save atomic stopping rule results in simulations and report them

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#124]
See discussion in #94 

To do:
Add design doc covering
- [ ] include current prototype using modified simulation function for reference / starting point
- [ ] how to unpack combined stopping rules such as `stopping = (A & B) | C | D` with atomic A, B, C, D 
- [ ] how to save atomic stopping rule results in simulation object
- [ ] how to summarize these

**Comment by robertadamsbayer** [comment]
Hi @danielinteractive,

a hopefully not too stupid questions: Currently, we implemented the additional ops. characteristics for the stopping rules for "complex" rules, i.e. "unzipped" by StoppingAny or StoppingAll. I struggle a bit with finding the best way to implement the new approach when there is an atomic stopping rule provided for the simulation. 

We currently use "StoppingANY" or "StoppingALL" simulation methods (in DesignMethods) to create the stopping rule matrix and fill them with the made decisions (0 or 1) for each run before it is returned to the SimulationClass object. What would - from your perspective - be the right method to do similar for an atomic stopping rule? I seem to overlook the probably very simple and obvious choice here?! I would  think to do that in Rules-methods.R  - ("individual results"), in order to provide the required (1x1) matrix for the downstream frequency calculations. I feel however, that - from a code design perspective - it´s not the best choice to have completely different "locations" for the creation of structures that fit a similar purpose? I am almost sure that I miss something here?

**Comment by danielinteractive** [comment]
Thanks @robertadamsbayer , Indeed I would say that for atomic stopping rules this reporting does not add any information for the user, therefore it should not be done.

**Comment by 0liver0815** [comment]
@ClaraBeckBayer just made me aware of this question. I have a slightly different opinion. Even though I agree to @danielinteractive that one stopping rule leads to 100% stops assigned to that rule may not be very valuable as a result itself, I believe that there is some value in reporting the result for atomic stopping rules:
1. The user get the information which stopping rule was used (for later reference or may also be helpful comparing simulations using different atomic stopping rules) 
2. For consistency reasons it is worth to report the outcome always in the same way. I.e. if statistics about stopping reasons is reported, it may not be clear if stopping reasons are not reported at all, or if it is not reported because there is only one stopping rule used in the setup. This is also true when presenting the operation characteristics later in the protocol, a reader may expect to see a section about stopping rules in the reported OC

**Comment by danielinteractive** [comment]
@0liver0815 Interesting - so right now the user would not know which stopping rule was used at all if it was an atomic one? I probably should remember this, but can you maybe share a screenshot or so?

**Comment by 0liver0815** [comment]
When thinking about you comment, I am not sure if I misunderstood the initial question. I am coming from the reporting perspective, i.e. I would like to have a summary of the simulations that reports how often a stopping rule was hit, regardless of if only one or multiple stopping rules are set up.
I believe that currently the simulation object contains a slot were all stopping rules that were set up, are reported with a text from which one can read if hit or not. This is also true if only one rule is set up. However, as it is only text, it cannot easily be evaluated for the OC.
The new approach try to support the reporting. So, my thought was that it is the best to always return if a stopping rule is hit or not.
I hope I am clear enough.

**Comment by danielinteractive** [comment]
thx @0liver0815 , so basically the current operating characteristics table does not include the stopping rule at all yet, correct? in that case yes, makes sense to have it included there and just say 100% of times the stopping rule was met

**Comment by 0liver0815** [comment]
That's correct. I fully agree. Thanks.

**Comment by ClaraBeckBayer** [comment]
Hi @0liver0815, 
I changed the script respectively. Could you check and let me know if this works now as you expected?  (Branch 124)

**Comment by 0liver0815** [comment]
@ClaraBeckBayer 

I gone through the proposed stopping rule text and have the following proposals (all for discussion):

Change the stopping section header of the summary function from
Stopping rules:
to
Stopping reason(s):

For the resulting text I have the following proposal:

- First comment line is the current text
- Second is my proposal

```
# "≥ 4 cohorts"
# Minimum number of 4 cohorts reached
as.character(StoppingMinCohorts(nCohorts = 4))

# "≥ 5 cohorts in 76 % of NBD"
# ≥ 5 cohorts in 76% dose range around NBD
as.character(StoppingCohortsNearDose(n=5,percentage = 76))

"≥ 5 patients in 75 % of NBD"
# ≥ 5 patients in 75% dose range around NBD
as.character(StoppingPatientsNearDose(nPatients=5,percentage = 75))

# "≥ 5 patients dosed"
# Minimum number of 5 patients reached
as.character(StoppingMinPatients(nPatients = 5))

# "[ 0.2 ≤ prob(DLT | dose) ≤ 0.35 ] for NBD ≥ 0.5"
# [0.2 ≤ prob(DLT | NBD) ≤ 0.35] ≥ 0.5"
as.character(StoppingTargetProb(target=c(0.2,0.35),prob=0.5))

# "≥ 0.9 prob MTD ( prob(DLE) = 0.33 ) > 0.5  * next dose"
# P(MTD > 0.5  * NBD | P(DLE) = 0.33) C 0.9
as.character(StoppingMTDdistribution(target=0.33,thresh=0.5,prob=0.9))

# "CV of target tox prob for MTD 0.3 ≤ 40 %"
# CV(MTD | P(DLE) = 0.3) ≤ 40 %
as.character(StoppingMTDCV(target=0.3, thresh_cv=40))

# "≥ 0.5 prob biomarker target range in [ 0.9 , 1 ] ( relative )"
# P( 0.9 ≤ Biomarker ≤ 1) ≥ 0.5 (relative)
as.character(StoppingTargetBiomarker(target = c(0.9, 1), scale="relative", prob = 0.5))

# "≥ 0.6 prob biomarker target range in [ 10 , 20 ] ( absolute )"
# P( 10 ≤ Biomarker ≤ 20) ≥ 0.6 (absolute)
as.character(StoppingTargetBiomarker(target = c(10, 20), scale="absolute", prob = 0.6))

# highest dose reached
# "Reached highest dose"
as.character(StoppingHighestDose())

# "TD 5 for 0.3 target prob"
# ?: CI ratio of TD ≤ 5 (P(DLE)=0.3)
as.character(StoppingTDCIRatio(targetRatio = 5,targetEndOfTrial = 0.3))

# "GStar 5 for 0.3 target prob"
# ?: CI ratio of Gstar ≤ 5 (P(DLE)=0.3)
as.character(StoppingGstarCIRatio(targetRatio = 5,targetEndOfTrial = 0.3))
```

**Comment by gunhanb** [comment]
I would also prefer the way Oliver revised the comments, that is having comments more human readable.

**Comment by ClaraBeckBayer** [comment]
@0liver0815, @danielinteractive 
Who could help with the last two rules to replace the questionnaire there?

**Comment by danielinteractive** [comment]
@ClaraBeckBayer I would be happy to help, but sorry where is it? can you reference a line in the code or in the PR? or repeat here?

**Comment by ClaraBeckBayer** [comment]
> @ClaraBeckBayer
> 
> I gone through the proposed stopping rule text and have the following proposals (all for discussion):
> 
> Change the stopping section header of the summary function from Stopping rules: to Stopping reason(s):
> 
> For the resulting text I have the following proposal:
> 
> * First comment line is the current text
> * Second is my proposal
> 
> ```
> # "≥ 4 cohorts"
> # Minimum number of 4 cohorts reached
> as.character(StoppingMinCohorts(nCohorts = 4))
> 
> # "≥ 5 cohorts in 76 % of NBD"
> # ≥ 5 cohorts in 76% dose range around NBD
> as.character(StoppingCohortsNearDose(n=5,percentage = 76))
> 
> "≥ 5 patients in 75 % of NBD"
> # ≥ 5 patients in 75% dose range around NBD
> as.character(StoppingPatientsNearDose(nPatients=5,percentage = 75))
> 
> # "≥ 5 patients dosed"
> # Minimum number of 5 patients reached
> as.character(StoppingMinPatients(nPatients = 5))
> 
> # "[ 0.2 ≤ prob(DLT | dose) ≤ 0.35 ] for NBD ≥ 0.5"
> # P(0.2 ≤ prob(DLE | NBD) ≤ 0.35) ≥ 0.5
> as.character(StoppingTargetProb(target=c(0.2,0.35),prob=0.5))
> 
> # "≥ 0.9 prob MTD ( prob(DLE) = 0.33 ) > 0.5  * next dose"
> # P(MTD > 0.5  * NBD | P(DLE) = 0.33) ≥ 0.9
> as.character(StoppingMTDdistribution(target=0.33,thresh=0.5,prob=0.9))
> 
> # "CV of target tox prob for MTD 0.3 ≤ 40 %"
> # CV(MTD | P(DLE) = 0.3) ≤ 40 %
> as.character(StoppingMTDCV(target=0.3, thresh_cv=40))
> 
> # "≥ 0.5 prob biomarker target range in [ 0.9 , 1 ] ( relative )"
> # P( 0.9 ≤ Biomarker ≤ 1) ≥ 0.5 (relative)
> as.character(StoppingTargetBiomarker(target = c(0.9, 1), scale="relative", prob = 0.5))
> 
> # "≥ 0.6 prob biomarker target range in [ 10 , 20 ] ( absolute )"
> # P( 10 ≤ Biomarker ≤ 20) ≥ 0.6 (absolute)
> as.character(StoppingTargetBiomarker(target = c(10, 20), scale="absolute", prob = 0.6))
> 
> # highest dose reached
> # "Reached highest dose"
> as.character(StoppingHighestDose())
> 
> # "TD 5 for 0.3 target prob"
> # ?: CI ratio of TD ≤ 5 (P(DLE)=0.3)
> as.character(StoppingTDCIRatio(targetRatio = 5,targetEndOfTrial = 0.3))
> 
> # "GStar 5 for 0.3 target prob"
> # ?: CI ratio of Gstar ≤ 5 (P(DLE)=0.3)
> as.character(StoppingGstarCIRatio(targetRatio = 5,targetEndOfTrial = 0.3))
> ```

Hi @danielinteractive, 
sorry, I was referring to this post from Oliver.

**Comment by 0liver0815** [comment]
@ClaraBeckBayer; @danielinteractive

I reviewed the stopping rule text for the last two again and I think that the text should probably be harmonized with the proposal for 

```
# "CV of target tox prob for MTD 0.3 ≤ 40 %"
# CV(MTD | P(DLE) = 0.3) ≤ 40 %
as.character(StoppingMTDCV(target=0.3, thresh_cv=40))
```

If I am not mistaken, the stopping rules  `StoppingMTDCV`, `StoppingTDCIRatio` and `StoppingGstarCIRatio`  determine the dose where the toxicity is equal to the target and derive the CV or the CI for that dose. I.e. it is a stopping criteria that stops when the target dose can be estimated with sufficient precision.
So the new proposal is:

```
# "TD 5 for 0.3 target prob"
# 95% CI ratio(TD | P(DLE)=0.3) ≤ 5
as.character(StoppingTDCIRatio(targetRatio = 5, targetEndOfTrial = 0.3))

# "GStar 5 for 0.3 target prob"
# 95% CI ratio(Gstar | P(DLE)=0.3) ≤ 5
as.character(StoppingGstarCIRatio(targetRatio = 5, targetEndOfTrial = 0.3))
```
I think we agreed that this could be implemented for now as is (when the text is not completely misleading) and refined later, when we think that the text is not optimal.

**Comment by danielinteractive** [comment]
closing this one as we now have a good idea what to do and it is difficult to put this in design doc format as we need to change existing classes. working on this in #94 (issue) and #426 (PR)
