### ISSUE TITLE
simplify `mcmc` section in model related class unit tests

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#142]
To do:

- [x] use something like `expect_snapshot_value` with tolerance
- [x] small helper function wrapper to reduce code needed each time

For example:
Instead of https://github.com/Roche/crmPack/blob/e5080fec2781ec545ba1d10ea5d4234cc4554f85/tests/testthat/test-Model-class.R#L104 could have something like:
`h_expect_value_tol(result@data)`

**Comment by wwojciech** [comment]
Hi @danielinteractive 
I have been trying to use `expect_snapshot_value` with the `tolerance` argument but this function gives some esoteric errors, even when you do something like:
```
test_that("test_snap", {
  expect_snapshot_value(1:4)
})
```

```
Error in `check_roundtrip(value, load(value_enc), ..., tolerance = tolerance)`: Serialization round-trip is not symmetric.

`value` is an integer vector (1, 2, 3, 4)
`roundtrip` is a list

i You may need to consider serialization `style`
Backtrace:
 1. testthat::expect_snapshot_value(1:4)
      at test-Model-class.R:327:2
 2. testthat:::expect_snapshot_helper(...)
 3. snapshotter$take_snapshot(...)
 4. testthat:::check_roundtrip(value, load(value_enc), ..., tolerance = tolerance)
```

So I thought it would be actually ok to use `expect_snapshot` which works fine and I think there is default tolerance in this.

**Comment by danielinteractive** [comment]
@wwojciech ok I think this is fine, we anyway don't have full precision in the snapshots
