### ISSUE TITLE
doseFunction-GeneralModel and probFunction-GeneralModel - handle params when array

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#154]
In doseFunction-GeneralModel (and probFunction-GeneralModel):

```
samples <- Samples(
    data = model_params,
    options = McmcOptions(samples = length(model_params[[1]]))
)
```
model_params might ba also an array object, so length is not always appropriate. This should be corrected. See `h_null_if_scalar()` fun on how this can be handled.

**Comment by danielinteractive** [comment]
@wwojciech you could also use `NROW()` which works on vectors and arrays

**Comment by wwojciech** [comment]
Thanks @danielinteractive!, I did not know this fun!

**Comment by wwojciech** [comment]
Using this issue, I removed also `h_null_if_scalar` function which is now (due to https://github.com/Roche/crmPack/issues/449) not needed anymore.
