### ISSUE TITLE
DualEnpoint constructor, init function with arguments?

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#155]
Are these arguments needed to init function needed in `DualEnpoint` constructor? 

```
init = function(y, w, nGrid) {
    c(init, list(z = ifelse(y == 0, -1, 1), theta = c(0, 1)))
}
```

**Comment by danielinteractive** [comment]
@wwojciech hm, seems only `y` is needed, as well as previous `init`?

**Comment by wwojciech** [comment]
Confirmed. Tx @danielinteractive!
