### ISSUE TITLE
Unit tests snapshots for long erorrs

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#165]
In unit tests, for error message check, when there are many error messages to check - we can use snapshot. See below example from: `test-Model-validity.R`
```
test_that("v_model_dual_endpoint_beta returns error for wrong use_fixed", {
  object <- h_get_dual_endpoint_beta()
  # Assigning non-valid use_fixed.
  object@use_fixed <- TRUE

  expect_snapshot(v_model_dual_endpoint_beta(object))
})
```
This issue is to briefly check existing unit tests and see whether we can use snapshots instead of fixed error messages.

**Comment by danielinteractive** [comment]
For readability of the tests itself, snapshots are always a bit problematic. So in this case I think it is better to have the error messages directly in the test.
