### ISSUE TITLE
remove `ModelLogNormal` class as it does not bring any significant value

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#169]
remove `ModelLogNormal` class as it does not bring any significant value

**Comment by wwojciech** [comment]
@danielinteractive 
I reviewed this issue a bit more deeply, checked alternative coding and etc. It seems that `ModelLogNormal` still provides reasonable simplification, particularly it allows to avoid duplication of roxygen help entries and etc. So I think I would keep this.

**Comment by danielinteractive** [comment]
@wwojciech alright, let's keep it
