### ISSUE TITLE
In unit tests of user construction: test if argument values were passed to the slot. 

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#175]
It would be valuable to test that all of the class object slots were indeed initiated correctly according to the values of the arguments in user constructor call.
For example, below is the the constructor for `DualEndpoint` class and the definition of the class itself. In the new unit test, we need to make sure that, e.g. when we call `DualEndpoint(mean = 1, cov = 2, ref_dose = 4, sigma2W = 10, rho = 0.5)`, then, e.g.  `DualEndpoint@rho` will indeed get a value  of `0.5` rather than it stays at its default `0`. 

The need of this new type of unit test is actually driven by the bug that appeared in the old implementation of `DualEndpoint()`, where constructor did not use the values of some of its arguments in the way described above.

```
DualEndpoint <- function(
  mean,
  cov,
  ref_dose = 1,
  use_log_dose = FALSE,
  sigma2W,
  rho
)

.DualEndpoint <- setClass(
  Class = "DualEndpoint",
  slots = c(
    betaZ_params = "ModelParamsNormal",
    ref_dose = "positive_number",
    use_log_dose = "logical",
    sigma2W = "numeric",
    rho = "numeric",
    use_fixed = "logical"
  ),
  prototype = prototype(
    betaZ_params = ModelParamsNormal(
      mean = c(0, 1),
      cov = diag(2)
    ),
    ref_dose = positive_number(1),
    use_log_dose = FALSE,
    sigma2W = 1,
    rho = 0,
    use_fixed = c(
      sigma2W = TRUE,
      rho = TRUE
    )
  ),
  contains = "Model",
  validity = v_model_dual_endpoint
)
```

**Comment by wwojciech** [comment]
Hi @danielinteractive - FYI, what do you think on this issue? We discussed it briefly some time ago, but just wanted to double check before I start to work on it, as this would be a bit time consuming case, as we would need this for all the clases Tx!

**Comment by danielinteractive** [comment]
Hi @wwojciech I would say this is good but low priority. E.g. when I am on vacation some time then this would be a good one to work on, because you don't need any input from my side

**Comment by wwojciech** [comment]
Perfect; let's do it in this way! Thank you @danielinteractive

**Comment by danielinteractive** [comment]
Will be part of conventions in contributing guide.
