### ISSUE TITLE
`Data` clean up 

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#20]
To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] for classes:
    - [x] test default constructor
    - [x] for reference classes: test methods
  - [x] for functions: as usual
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] keep externally used names so that we don't break downstream code
  - [x] consider renaming internal variables etc. if needed
  - [x] if a function is too long, break up into pieces
  - [x] for classes: move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
  - [x] in `setClass` function, just use the `slots` instead of outdated `representation`.
  - [x] Remove things like `validObject(.Data())`

**Comment by wwojciech** [comment]
Hi @danielinteractive, in the help for a class/function, when we described parameters, should I use the R type or S3 class name? For example for slot `x` in class `Data`, it is type `double` but S3 class name `numeric`, so
```
#' @slot x (`double`)\cr the doses for the patients.
```
or 
```
#' @slot x (`numeric`)\cr the doses for the patients.
```
would be preffered?

Thanks!

**Comment by danielinteractive** [comment]
@wwojciech `numeric` please. Generally we take the class names. See details here: https://nest.pages.roche.com/docs/dev-guide/coding/documentation/
