### ISSUE TITLE
FractionalCRM - possible bug in the existing code for `modelspecs`?

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#213]
https://github.com/Roche/crmPack/blob/bba66bba857cc58fbadd61e4da4f9255cf59e286/R/Model-class.R#L2759

I think it should be: 
```
if (u[k] < Tmax && y[k] == 0L)
```
What do you think @danielinteractive ?

**Comment by danielinteractive** [comment]
@wwojciech yeah looks like, thx for seeing that!

**Comment by wwojciech** [comment]
Thanks @danielinteractive !
