### ISSUE TITLE
Set default values for some args in user construction functions.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#260]
Set default values for some args in user construction functions. For example, for the following it would be good that `target` and `derive` have default values of in the class' prototype.

```
NextBestMTD <- function(target, derive) {
  .NextBestMTD(
    target = target,
    derive = derive
  )
}
```

This applies for the following classes, methods: `Data`, `McmcOptions`, `Model`.

Alternative: #325

**Comment by danielinteractive** [comment]
Handled in #325
