### ISSUE TITLE
assert_* in use constructor vs. validate functions

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#30]
Hi @danielinteractive 

This is to clarify the strategy for input verification for user class constructors. 
On one hand we can use `checkmate::assert_*` checks at the beginning of user constructor function. On the other, classes provide their own validation methods to check the if the slots are initiated properly.

I wanted to avoid some duplicated checks here and hence this issue to discuss this problem further and to clarify it. While I understand that sometimes we may use `checkmate::assert_*` inside user constructor to verify something which will be required by some computations by the constructor itself, before the default class constructor is called - and this is clear - but in most cases, the input will be again validated by the validity function of the class. So for instance `Data` class user constructor where in fact all of the `checkmate::assert_*` checks are repeated with the `validate_data` validate function.

**Comment by danielinteractive** [comment]
@wwojciech yeah thanks for asking and bringing this up. It really depends what happens inside the user constructor function. 
For example, if in the user constructor we have something like

```r
# [...]
if (bla) {
  x <- seq_len(n)
}
```

and we pass `bla` and `n` as arguments then we should have assertions `assert_flag(bla)` and `assert_number(n)` to make sure that the code is well defined here. We need those, even when `bla` and `n` would later be passed to the default constructor and be validated there. 
So for me, that is the only functionality of assertions in user constructors - and any other function in fact: make sure that the current function code can work as expected.

Does that resolve the question?

**Comment by wwojciech** [comment]
Yes, thank you @danielinteractive
