### ISSUE TITLE
Improve Readme and factor out into new "introduction" vignette

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#319]
To do:

- [x] new "introduction" vignette:
	- [x] add more explanation 
	- [x] add formula for the model definition
	- [x] add results
	- [x] make dose grid more regular
- [x] keep Readme very short and just have Installation and cross references (vignette calls) for the vignettes

**Comment by PuzzledFace** [comment]
Need to write new vignette for trial design and integrate JSS paper vignette.

**Comment by danielinteractive** [comment]
@PuzzledFace I think it would be sufficient to include the relevant bits and pieces from the JSS paper, but no need to try to integrate the whole vignette. For now for this issue here I would keep it focused on introducing a new user to the package, and e.g. not mention more than necessary on the package structure etc.

**Comment by PuzzledFace** [comment]
Fixing broken hyperlinks

**Comment by wwojciech** [comment]
Blocked by: #435

**Comment by danielinteractive** [comment]
This can be closed as the PR was merged.
