### ISSUE TITLE
Add “O’Quigley arctan model” from the JSS paper into the package

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#321]
To do:

- [ ] Take classes and methods from the JSS paper into the package
- [ ] add tests

JSS Paper: https://www.jstatsoft.org/article/view/v089i10

**Comment by danielinteractive** [comment]
@0liver0815 is this still needed?

**Comment by 0liver0815** [comment]
I think it still make sense to include the model in the package, even if the only difference to the `OneParExpNormalPrior` is the definition of the prior. https://github.com/Roche/crmPack/blob/0b0d99967abea95f8b517672150934f3f3180767/R/Model-class.R#L2639
I already thought about having only one class that covers both priors (normal and exp prior), e.g. `OneParExp`, but I am not sure if this is better than having two separate classes.

**Comment by danielinteractive** [comment]
@0liver0815 cool, I understand, sounds good to me to add this as separate class. maybe use a similar class name
