### ISSUE TITLE
Design broom-like `tidy()` and `glimpse()` methods

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#323]
To do:

- [x] Add design doc in `design` folder
- [x] Describe idea
- [ ] Think about potentially different solution paths
- [ ] Discuss questions such as 
	- [ ] whether to include attributes of the whole object in each row of the data frame
- [ ] Add prototype code

**Comment by PuzzledFace** [comment]
Some classes, such as `StioppingRuleTargetProb`, specify ranges in unnamed vectors:

```
StoppingTargetProb(target=c(0.2, 0.35), prob=0.5)
```
Currently, the `tidy()` generic converts this to:
```
# A tibble: 2 × 3
  Class              target  prob
  <chr>               <dbl> <dbl>
1 StoppingTargetProb   0.2    0.5
2 StoppingTargetProb   0.35   0.5
```

Would this be better represented as

```
# A tibble: 1 × 4
  Class               prob   min   max
  <chr>              <dbl> <dbl> <dbl>
1 StoppingTargetProb   0.5   0.2  0.35
```

I think yes.

Here's a draft list of classes that are potentially affected:

```
StoppingtargetBiomarker
StoppingTargetProb
```

**Comment by danielinteractive** [comment]
Is now being worked on in #587 therefore closing here
