### ISSUE TITLE
Add no-argument constructors for all classes

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#325]
Motivation: For downstream shiny and maybe other code development it could be useful to have a construction of any object without specific arguments.

To do:

- [ ] Go through all classes (extract e.g. from NAMESPACE file) and put them here in a checklist:
	- [ ] e.g. `Data`
	- [ ] etc.
- [ ] For each class, add a default no-argument constructor that prefixes the class name with `.Default`:
	- [ ] `.DefaultData()`
	- [ ] etc
- [ ] add tests (to make sure it works)
- [ ] document in the same page as the user constructor
- [ ] export those (so it can be used in add on packages / shiny apps by the user etc.)

Alternative: #260

**Comment by wwojciech** [comment]
Hi @danielinteractive - if I understand this correctly, this means that some default values for the class' slots should be hardcoded in the class' user constructor? Or should we just define a default values for the slots in prototype of class, and then the user no-args constructor would be just simply `A <- function() { .A() }` (wherever possible)

**Comment by danielinteractive** [comment]
@wwojciech Yes, reasonable default values should be present in this no-argument default constructor, naming convention `.DefaultClass()` where `Class` is the usual class name. If we can achieve this with prototype in the class definition, nice, if not, then need additional slot initialization.

**Comment by wwojciech** [comment]
Yap, using prototype would be the best I think, but requires a bit more changes. Lets see.

**Comment by PuzzledFace** [comment]
@wwojciech suggested, for example,

```
eval(parse(text=".StoppingMinCohorts()))
```

or
```
do.call(".StoppingCohortsNearDose", args = list())
```

but this currently has problems, both of validity and usefulness.  For example

```
.ModelParamsNormal()
An object of class "ModelParamsNormal"
Slot "mean":
numeric(0)

Slot "cov":
<0 x 0 matrix>

Slot "prec":
<0 x 0 matrix>
validObject(.ModelParamsNormal())
Error in eigen(x, only.values = TRUE) : 0 x 0 matrix
```
which is inconsistent with
```
validObject(.LogisticLogNormal())
```

Since `.LogisticLogNormal()@params` is a `ModelParamsNormal` object identical to the above.

**Comment by danielinteractive** [comment]
Thanks @PuzzledFace , yeah I think we need a different name and definition for these constructor functions since some classes require further slot manipulation after initialization. 

Generally I would be tending to explicit definitions for these rather than automatically constructed ones.

**Comment by wwojciech** [comment]
@PuzzledFace - I think this is not a problem. Why not to define a `"reasonable default values"` (as @danielinteractive suggested few posts above), so that validation passes for the "default" object, regardless of whether it was created with `.<name>()` or `<name>()`.

**Comment by PuzzledFace** [comment]
Personally, I prefer the idea of a factory method/class over a no-argument constructor.  My reason is the one we have discussed in the past: no argument constructors increase the risk of unknowing or accidental user error.  For example, the case of a `ref_dose`, when no default value can be appropriate for every dose grid.  if users aren't aware of the need to check `ref_dose` against their specific dose grid, problems can occur.  We have at least one real-life example of when this might happen.

I think the programmatic generation of `crmPack` objects is going to be most useful in unit testing and app development. So use a factory class/method here and avoid the use of no argument constructors in day-to-day use, thus helping to protect end users from accidental mistakes.

I will create a separate issue/pull request to make the factory method I've written for `shinyCrmPack` available for review.

**Comment by danielinteractive** [comment]
Thanks John, but I would think that by using `.Default` as prefix and clearly documenting this users won't accidentally use those constructors in the first place?

My concern is that it is going to be difficult to use factories for model classes. But if you have a good idea for that a draft PR will be interesting.

Another consideration could be that if we only need this for the shiny interface anyway, we might also include this in the separate shiny crmPack package?

**Comment by PuzzledFace** [comment]
@danielinteractive Ah!  I'd missed the point that no argument constructors would have a `.Default` prefix.  That makes sense and I agree this would reduce the risk of a mistake by the end user.  So, with this naming convention, I have no preference between factory method and class-specific no-argument constructor.

Yes, this functionality *could* stay in `shinyCrmPack`.  It's unlikely that *users*  will need it.  But, as I demonstrated last week, *developers* may find it helpful in unit testing.  I think that's potentially a good enough reason to add it to `crmPack` itself.
