### ISSUE TITLE
plot method for `Data` clean up 

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#33]
To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] Remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] For classes:
    - [x] Test default constructor
    - [x] For reference classes: test methods
  - [x] For functions: as usual
    - [x] for plot functions/methods use `vdiffr` to compare current test result with original plot
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] Keep externally used names so that we don't break downstream code
  - [x] Remove `keywords` tags
  - [x] For functions or methods:
    - [x] Add assertions for arguments using `checkmate` functions
    - [x] If it is too long, break up into pieces (rule of thumb: maximum 50 lines of code)
    - [x] Consider renaming internal variables etc. if needed
    - [x] Avoid explicit use of `return`
  - [x] For classes:
    - [x] move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
    - [x] In `setClass` function, just use the `slots` instead of outdated `representation`
    - [x] Remove things like `validObject(.Data())`

**Comment by wwojciech** [comment]
Hi @danielinteractive I see that in methods, the names of the argument for the object is `x`. I noticed in `helios` you use `object` as a first parameter and I think this is more intuitive. I think I would like to change the name from `x` to `object`, but I we agreed that we will be careful with changing a user interface. What do you think Daniel? Tx!

**Comment by danielinteractive** [comment]
@wwojciech the point is that the generic function `plot` has an `x` argument, therefore we keep it (and need to) at that.

**Comment by wwojciech** [comment]
Hi @danielinteractive I have just pushed my commit for the update plot function, without unit tests. I wanted to check this with you  before proceeding with unit tests. Tx!
