### ISSUE TITLE
Closes #220 (new branch based on latest main) 

### ISSUE THREAD

**Issue by gunhanb** [Roche/crmPack#335]
Summary
As mentioned before, we have written code to compare crmPack functions (Data, mcmc etc) with published results (Neuenschwander et al, 2008 paper).

I suggest that I can create an R file (named "test-mcmc-accuracy") for the attached code.

Reference
Neuenschwander, B., Branson, M. and Gsponer, T. (2008), Critical aspects of the Bayesian approach to phase I cancer trials. Statist. Med., 27: 2420-2439. https://doi.org/10.1002/sim.3230

Prototype
[test_crmPack_literature.txt](https://github.com/Roche/crmPack/files/9581580/test_crmPack_literature.txt)

**Comment by danielinteractive** [comment]
@gunhanb this is an issue, not a PR - did you plan to do a PR maybe? just guessing based on the title
