### ISSUE TITLE
plot method for `DataDA` clean up 

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#35]
To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] Remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] For classes:
    - [x] Test default constructor
    - [x] For reference classes: test methods
  - [x] For functions: as usual
    - [x] for plot functions/methods use `vdiffr` to compare current test result with original plot
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] Keep externally used names so that we don't break downstream code
  - [x] Remove `keywords` tags
  - [x] For functions or methods:
    - [x] Add assertions for arguments using `checkmate` functions
    - [x] If it is too long, break up into pieces (rule of thumb: maximum 50 lines of code)
    - [x] Consider renaming internal variables etc. if needed
    - [x] Avoid explicit use of `return`
  - [x] For classes:
    - [x] move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
    - [x] In `setClass` function, just use the `slots` instead of outdated `representation`
    - [x] Remove things like `validObject(.Data())`

**Comment by wwojciech** [comment]
Hi @danielinteractive I complete cleaning the plot methods for data classes. Now, when I look at it overall, I think that there are some blocks of plotting code which are used by all three methods and therefore it might be beneficial to consider to extract it into a separate funs. For example: `plot_data_add_cohort_lines()` which would create green lines separating cohorts. What do you think Daniel? Tx!

**Comment by danielinteractive** [comment]
@wwojciech sounds great. let's avoid duplicate code as much as we can in general.

**Comment by danielinteractive** [comment]
you can do that in new issue/PR to keep things moving.
