### ISSUE TITLE
Models: calculation of prob and dose for a single model parameters

### ISSUE THREAD

**Issue by 0liver0815** [Roche/crmPack#362]
To do:

- [x] add a new vignette "Migrating from old `crmPack`" and include a section on this there
- [x] add to introduction vignette

With the new representation of models, it may be unclear to users how a probability can be derived for a certain dose and vice versa with fixed model parameters (a single parameter).
After discussion with @wwojciech, I was able to do the calculation, but I think that this should be put into the documentation (vignette?), so that end users are able to do the calculation. 

```
empty_data <- Data(doseGrid = c(1, 3, 5, 10, 15, 20, 25, 40, 50, 80, 100))

my_model <- LogisticNormal(
  mean = c(-0.85, 1),
  cov = matrix(c(1, -0.5, -0.5, 1), nrow = 2)
)

my_options <- McmcOptions(burnin = 10, step = 2, samples = 100)

samples <- mcmc(empty_data, my_model, my_options)

dose(0.3, my_model, samples)
my_dose <- doseFunction(my_model, alpha0 = mean(my_samples@data$alpha0), alpha1 = mean(my_samples@data$alpha1))
my_dose(0.3)

prob(10, my_model, samples)
my_prob <- probFunction(my_model, alpha0 = mean(my_samples@data$alpha0), alpha1 = mean(my_samples@data$alpha1))
my_prob(10)

```

**Comment by wwojciech** [comment]
I created just one vignette so that new users of `crmPack` are not confused with some old staff.

**Comment by wwojciech** [comment]
Hi @danielinteractive , @0liver0815 

I was thinking a bit more on this `dose`, `doseFunction` staff. I think, it can be done without `doseFunction`. For example:
```
setMethod(
  f = "dose",
  signature = signature(
    x = "numeric",
    model = "LogisticNormal",
    samples = c("Samples", "missing")
  ),
  definition = function(x, model, samples, ...) {
    if(missing(samples)) {
      model_params <- list(...)
      samples <- Samples(
        data = model_params,
        options = McmcOptions(samples = length(model_params[[1]]))
      )
    }

    assert_subset(c("alpha0", "alpha1"), names(samples@data))
    alpha0 <- samples@data$alpha0
    alpha1 <- samples@data$alpha1
    ref_dose <- as.numeric(model@ref_dose)
    assert_probabilities(x, len = h_null_if_scalar(alpha0))

    exp((logit(x) - alpha0) / alpha1) * ref_dose
  }
)
```
Then, user can just use:
```
dose(0.3, my_model, my_samples)
```
or
```
dose(0.3, my_model, alpha0 = -0.8, alpha1 = 1)
```

**Comment by danielinteractive** [comment]
@wwojciech yes, possible, but seems too much overhead for maintenance and creation of these additional methods

**Comment by wwojciech** [comment]
Hmm, but we sometimes need `dose(0.3)` and this is the only one problem. So the question is probably if we really need `dose(x)`

**Comment by wwojciech** [comment]
> @wwojciech yes, possible, but seems too much overhead for maintenance and creation of these additional methods

actually, these methods are already created, you would just need to add the `if` clause.

**Comment by danielinteractive** [comment]
Still too much overhead for too little value - let's keep as is and document in the vignette as planned
