### ISSUE TITLE
`NextBestNCRMLoss` - `overdose` and `unacceptable` slot revisited

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#364]
Hi @gunhanb 

I think the `NextBestNCRMLoss` class should be revisited. That is, if the lower limits of these 2 intervals: `overdose` and `unacceptable`, are excluded, why `0` is not allowed then? I think we could easily allow `0` as it is excluded anyway?
What do you think?

**Comment by wwojciech** [comment]
Hi @gunhanb - can you pl. comment on this? Thanks!

**Comment by wwojciech** [comment]
Hi @gunhanb - this is a friendly reminder about this issue. This issue is about your code and requires your input. Thank you.

**Comment by gunhanb** [comment]
Hi @wwojciech  Very sorry for mylate reply! Yes, exactly I agree with you. As you said lower bounds are excluded anyways.

**Comment by wwojciech** [comment]
> Hi @wwojciech Very sorry for mylate reply! Yes, exactly I agree with you. As you said lower bounds are excluded anyways.

Perfect, thanks a lot! So I will correct it.

**Comment by gunhanb** [comment]
Yes, thank you very much!
