### ISSUE TITLE
OneParExpNormalPrior mismatch of slots in class and param in constructor

### ISSUE THREAD

**Issue by 0liver0815** [Roche/crmPack#370]
I am not sure if this is an issue, but when I started to move the test that the `skel_probs` should be of the same length as the `dose_grid` to `v_model_one_par_exp_normal_prior` I realized that `dose_grid` is only a parameter and not a slot. In addition `skel_fun_inv` and `skel_fun` are slots, but no parameters.
I am wondering if this is correct and why it is constructed in this way.

https://github.com/Roche/crmPack/blob/d7cb6def0d43ba7cffbb439b367feda027934991/R/Model-class.R#L2581-L2584
https://github.com/Roche/crmPack/blob/d7cb6def0d43ba7cffbb439b367feda027934991/R/Model-class.R#L2607-L2609

**Comment by danielinteractive** [comment]
I think this is because `dose_grid` is a property i.e. slot of `Data` class.

**Comment by 0liver0815** [comment]
dose_grid it not connected to `Data` class. It can be any vector, e.g. `c(1,7,20,21,21.1)` independent from any data.

**Comment by 0liver0815** [comment]
I think I understand why `skel_fun` and `skel_fun_inv` are slots. They are needed in `prob-OneParExpNormalPrior` and `dose-OneParExpNormalPrior`.
I believe that `dose-grid` is probably not needed at all, as it can be any vector of the length of skel_prob. The actual doses are always defined in the `Data` object.

**Comment by danielinteractive** [comment]
@0liver0815 yep technicall `dose_grid` is not needed but it provides a first check for the user if the model they are setting up with the skeleton matches in terms of length to the `dose_grid` they are using in their data object

**Comment by 0liver0815** [comment]
Ok. Thanks for the dicussion. I will close the issue. Everything can remain as is.
