### ISSUE TITLE
Create new custom checkmate: test_range

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#390]
A kind of a wrapper for:
```
test_numeric(x, finite = TRUE, any.missing = FALSE, len = 2, unique = TRUE, sorted = TRUE)
```

**Comment by wwojciech** [comment]
Hi @danielinteractive - do you think this makes sense? I think we would need it in 5 or 6 places (maybe more), this is actually not needed?

**Comment by danielinteractive** [comment]
@wwojciech I think it is a good idea, thanks
