### ISSUE TITLE
Error in v_model_objects validates that [`OneParExpNormalPrior`] class slots are valid

### ISSUE THREAD

**Issue by 0liver0815** [Roche/crmPack#393]
After error correction #367 it turns out that the validity checks for the slots do not work as specified

https://github.com/Roche/crmPack/blob/8d913a71ebfab84df35e6fdd7aad0bbf694d8f0b/R/Model-validity.R#L511-L519

As far as I can see, the problem is that fixed sequence of 11 probs is generated to check if the inverse function is correct. The problem after merging #367 is that no NA are returned anymore, but the highest or lowest dose in case that the prob is outside of the range of the skeleton probs.
I think the check will now fail anytime when the fixed sequence does not match the skeleton probs. I think the following code will solve the problem:
```
# user specified values:
dose_grid <- 1:11
skel_probs <- seq(0.1, 0.5, length.out=11)

# just helper to test easily (not necessary in model-validity.r
skel_fun <- approxfun(x = dose_grid, y = skel_probs, rule = 2)
skel_fun_inv <- approxfun(x = skel_probs, y = dose_grid, rule = 2)

# new test code:
x <- skel_fun_inv(skel_probs) # Dose grid.
all.equal(skel_fun(x), skel_probs)
```

**Comment by wwojciech** [comment]
> x <- skel_fun_inv(skel_probs) # Dose grid.
> all.equal(skel_fun(x), skel_probs)

Thanks @0liver0815 - that would be to too insensitive if we test `skel_fun_inv` only for the `skel_probs` which were used to build this function, i.e. we would have not effect of any interpolation at all, as we test it only at the fixed points. I will try to propose something what is sufficiently sensitive.
