### ISSUE TITLE
Snake case and Camel case: add some background explanation and logic 

### ISSUE THREAD

**Issue by 0liver0815** [Roche/crmPack#401]
The goal after the cleanup is that classes are using Camel case and parameters and slots are using Snake case. We should add some explanation and the logic to the documentation so that new and old users understand the logic and old users are aware that their code may need change in parameter names to run with the new version.

To do:
- [ ] Add paragraph on this to the relevant part in https://github.com/Roche/crmPack/blob/main/vignettes/migration_from_the_old_crmPack.Rmd

**Comment by danielinteractive** [comment]
@0liver0815 thanks for posting this! I cleared assignees for now. please only assign when starting work on a task.
