### ISSUE TITLE
NEWS update about variables names into a vignette.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#413]
I think it would be good if those detailed updates would be moved to a section in the migration vignette instead of being in the news. otherwise news gets too long. can do that as separate issue

_Originally posted by @danielinteractive in https://github.com/Roche/crmPack/pull/411#discussion_r1004720204_

**Comment by danielinteractive** [comment]
@wwojciech please in general only assign yourself as soon as you start working on it, not before, thanks
