### ISSUE TITLE
`crmPack-jss-paper.Rnw` does not sweave into pdf.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#435]
`crmPack-jss-paper.Rnw` does not sweave into a `pdf` file with the latest version (as of 2022 year) of LaTeX/pdflatex system. It fails with the following error after running 100% of the R code:
```
! LaTeX Error: Missing \begin{document}.
```
It works works well however for the old versions of LaTeX/pdflatex (dated back to 2020) - we checked it at Roche server where currently the old versions of LaTeX system is installed.

I am attaching the `.tex` and `.log` files from working systems for further reference.
[crmPack_jss_tex_log.zip](https://github.com/Roche/crmPack/files/10042271/crmPack_jss_tex_log.zip)

**Comment by Puzzled-Face** [comment]
resolved by #640
