### ISSUE TITLE
`probFunction`s should be vectorised

### ISSUE THREAD

**Issue by PuzzledFace** [Roche/crmPack#439]
A function obtained from `probFunction()` throws an exception when its `dose` parameter is passed a vector.  This causes inefficiency when used in, for example, a `data.frame` or tibble.  For example

```
postSamples5 <- mcmc(
  data = fifthFullCohort,
  model = model,
  options = vignetteMcmcOptions
)

fullSamples <- tibble(
                 Alpha = postSamples5@data$alpha0,
                 Beta = postSamples5@data$alpha1
               ) %>%
               expand(nesting(Alpha, Beta), Dose = doseGrid)
```
followed by
```
fullSamples %>% mutate(P=probFunction(model, alpha0=Alpha, alpha1=Beta)(dose=Dose))
```
produces
```
Error in `mutate_cols()`:
! Problem with `mutate()` column `P`.
ℹ `P = probFunction(model, alpha0 = Alpha, alpha1 = Beta)(dose = Dose)`.
✖ Assertion on 'dose' failed: Must have length 1, but has length 3888.
Caused by error in `.local()`:
! Assertion on 'dose' failed: Must have length 1, but has length 3888.
```

Whereas
```
fullSamples %>% 
  rowwise() %>% 
  mutate(P=probFunction(model, alpha0=Alpha, alpha1=Beta)(dose=Dose)) %>% 
  ungroup()
# A tibble: 3,888 × 4
   Alpha  Beta  Dose         P
   <dbl> <dbl> <dbl>     <dbl>
 1 -2.44 1.93      1 0.0000366
 2 -2.44 1.93      3 0.000305 
 3 -2.44 1.93      9 0.00255  
 4 -2.44 1.93     20 0.0118   
 5 -2.44 1.93     30 0.0255   
 6 -2.44 1.93     45 0.0541   
 7 -2.44 1.93     60 0.0907   
 8 -2.44 1.93     80 0.148    
 9 -2.44 1.93    100 0.211    
10 -2.20 0.584     1 0.0104   
# … with 3,878 more rows
```
works, but is hugely inefficient.

**Comment by wwojciech** [comment]
@danielinteractive  - FYI

This issue is about vectorising `prob/dose` functions. Lets use `prob` function as an example here. We currently handle the following 2 scenarios:

1. Length of the `model' params = 1`, then, `dose` can be of any length.
2.Length of the `model' params > 1`, then, `dose` must be length `1`.  

@PuzzledFace proposes to slightly extend scenario 2, i.e.

2a. Length of the `model' params > 1`, then, `dose` must of of length `1` or of the length of `model's params`.

This makes sense in my opinion.

**Comment by danielinteractive** [comment]
hm interesting. but for case 2a) when dose has the same length as the number of samples, I guess we would then match each dose to each MCMC sample? if that is useful in practice then yeah could be a nice addition.

**Comment by PuzzledFace** [comment]
@danielinteractive I don’t think the dose grid would ever have the same length as the number of samples.  That would be odd.

But I discovered the problem after creating a tibble by expanding a samples object from one-row-per-sample to one-row-per-dose-per-sample  (so that I could obtain the posterior estimate of p(DLT) for each combination of dose and sampled model parameters).  Currently, `probFunction` throws an error when I do this.  The workaround is to wrap the the `mutate()` in `rowwise()` … `ungroup()`.  But that’s unnatural and awkward.

**Comment by danielinteractive** [comment]
@PuzzledFace yeah that is what I meant. I did not assume that the dose grid itself would have the same length :-)

**Comment by wwojciech** [comment]
@danielinteractive , @PuzzledFace , so this would be just as an addition for an end-user, that if he provides a vector of model params and the vector of doses (all of the same len > 1), the output will be a `prob` vector of the same length, with 1:1 matching responses.

**Comment by wwojciech** [comment]
> hm interesting. but for case 2a) when dose has the same length as the number of samples, I guess we would then match each dose to each MCMC sample? if that is useful in practice then yeah could be a nice addition.

Exactly, so this would be just as an addition (in practice relevant only for an end-users of `dose/prob` funs), that if he provides vectors with  model' params and the vector of doses (all of the same len > 1), the output from `prob()` will be a `prob` vector of the same length, with element-wise matching responses.
