### ISSUE TITLE
Rename `OneParExpNormalPrior` class.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#445]
The old class `OneParExpNormalPrior` should become `OneParLogNormalPrior`, since `p = f(x) ^ exp(theta)`, where `theta ~ N`.

**Comment by 0liver0815** [comment]
Hi @wwojciech, you may probably want to add the additional test, checks and code changes from  #438.

**Comment by wwojciech** [comment]
> Hi @wwojciech, you may probably want to add the additional test, checks and code changes from #438. I can review if you think its useful.

Sure, thanks a lot @0liver0815. I think that all the changes are implemented now, except checking the slots for model class (skel_fun, skel_fun_inv) - as this is missing for many other functions and will be done through a separate issue.
