### ISSUE TITLE
Update `migration_from_the_old_crmPack` vignette about seed in `McmcOptions` class.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#446]
Add a new section in migration vignette `migration_from_the_old_crmPack` about seed setting for MCMC introduced in `crmPack::McmcOptions` class.

**Comment by wwojciech** [comment]
Hi @0liver0815 - FYI, I created the issue for this.

**Comment by 0liver0815** [comment]
Thanks @wwojciech!
