### ISSUE TITLE
Possibility to use parallel computing with extensions to the package

### ISSUE THREAD

**Issue by 0liver0815** [Roche/crmPack#487]
It is very easy to extend the crmPack functionality by own classes and methods. That works quite well and is sufficient for analysis of study data.
When generation operation characteristics is necessary, parallel computing is necessary. However, currently the code extensions that are not part of the installed package cannot be used, i.e. any code that is used during the parallel computing needs to be part of the installed R package.
The feature request is to make user written extension usable with parallel computing without creating and installing a new package.

**Comment by 0liver0815** [comment]
My first Idea was to create a wrapper function around the user written extension and export the the functions with parallel::clusterCall. I created a branch and added some code to test the general feasibility.
The code can be tested with [parallel_extension_LogisticNormalTruncPrior.R](https://github.com/Roche/crmPack/blob/487-parallel_computing_with_extensions/devel/parallel_extension_LogisticNormalTruncPrior.R) and [parallel_extension_test.r](https://github.com/Roche/crmPack/blob/487-parallel_computing_with_extensions/devel/parallel_extension_test.r)
Everything works as expected. i.e. parallel computing is possible.

@danielinteractive may I ask you to have a quick look, if this is a reasonable way to archive the goal (or probably you can advise, if you have an alternative idea, which I am happy to put into code and test).

**Comment by danielinteractive** [comment]
Thanks @0liver0815 , I think that is a good idea! Let's do this, i.e. best would be to have a vignette that explains this, could have a title similar like this issue title.
