### ISSUE TITLE
Non numeric argument in `mean.default(thisEffsamples@data$sigma2)`

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#500]
When running: `devtools::run_examples()`

many of the following warnings are seen:
```
In mean.default(thisEffsamples@data$sigma2) :
  argument is not numeric or logical: returning NA
```
I think it comes from `Design-methods.R`.

To do:
- [ ] Confirm the observation
- [ ] Replicate in unit test
- [ ] Find root cause
- [ ] Fix problem
- [ ] Confirm all tests pass

**Comment by Puzzled-Face** [comment]
I think this duplicates #586
