### ISSUE TITLE
Why do we require `clean_start >= dlt_start` for `IncrementsRelativeParts` objects?

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#516]
Hi @danielinteractive, I wanted to check with you on the following question.

Why do we require `clean_start >= dlt_start` for `IncrementsRelativeParts` objects? See the validation code below:
https://github.com/Roche/crmPack/blob/f041ae22d3991892257eaea30840ddbc804c73ac/R/Rules-validity.R#L240
When I am looking at the `maxDose-IncrementsRelativeParts` method it does not seem that this requirement is needed, see:
https://github.com/Roche/crmPack/blob/f041ae22d3991892257eaea30840ddbc804c73ac/R/Rules-methods.R#L1151

**Comment by danielinteractive** [comment]
Thanks @wwojciech , this is not for the code but for the semantics: if you observe a DLT you cannot be more aggressive than when you have a clean Part 1 without DLT
