### ISSUE TITLE
Avoid `default` messages when loading `crmPack`

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#522]
To do:
- [x] Temporarily add errors at https://github.com/Roche/crmPack/blob/main/R/Data-class.R#L126 when populating default IDs and cohort indices in `Data()` call
- [x] Set `options(error = recover)`
- [x] Install the package
- [x] Load the package and see where the error occurs
- [x] Modify the corresponding `Data()` call to avoid the on-load messages
- [x] Add a unit test that ensures silent behavior when loading `crmPack` with `library()` to avoid regression

Details:
There is a `Data()` usage somewhere without explicit `ID` and `cohort` specification in the package's code. This results in messages" **"Used ..".**, when loading the package. See below:
```
> devtools::load_all()
ℹ Loading crmPack
Used default patient IDs!
Used best guess cohort indices!
Used default patient IDs!
Used best guess cohort indices!
Creating a generic function for ‘get’ from package ‘base’ in package ‘crmPack’
Type crmPackHelp() to open help browser
Type crmPackExample() to open example
```
Within this issue, please find this place and specify `ID` and `cohort` explicitly. 
Note that, below does not lead to the problem mentioned.:
```
> devtools::load_all(reset = FALSE)
ℹ Loading crmPack
```

**Comment by PuzzledFace** [comment]
One place that generates the messages is the prototype for `GeneralSimulations`, starting at line 45 of `Simulations-class.R`.

**Comment by danielinteractive** [comment]
Hi @PuzzledFace do you have a separate PR for this one?

**Comment by PuzzledFace** [comment]
> Hi @PuzzledFace do you have a separate PR for this one?

No.  I fixed it whilst improving test coverage for Rules-methods.R.  Should I *always* keep different solutions in separate PRs in future?

**Comment by danielinteractive** [comment]
Ideally yes :-) that helps with keeping track of things and reviews. so then this can be closed?

**Comment by PuzzledFace** [comment]
> Ideally yes :-) that helps with keeping track of things and reviews. so then this can be closed?

Yes.  It can be closed.
