### ISSUE TITLE
For classes: add unit test that ensures that user constructor arg. names are as expected.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#529]
For example:
```
test_that("RuleDesign user constructor arguments names are as expected", {
  expect_function(
    RuleDesign,
    args = c("nextBest", "cohortSize", "data", "startingDose"),
    ordered = TRUE
  )
})
```
Note that this test brings added value as we check the order here, and with other, existing tests we intentionally do not specify argument names (so the order is checked but the arg names are not checked).

**Comment by danielinteractive** [comment]
I don't think this is needed as a unit test. We can have conventions around the user constructor signature, but this can go into #104
