### ISSUE TITLE
Rename some of the unit test helper functions.

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#531]
For unit test helper function defined in:
- `helper_data.R`
- `helper_model.R`
- `helper_modelparams.R`
- `helper_McmcOptions.R`

remove `_get` from the name of the function. 
For example: `h_get_data` should be renamed to `h_data`. 

This will be consistent with other unit test helpers and also remove this unnecessary word `get`.

**Comment by danielinteractive** [comment]
Not needed
