### ISSUE TITLE
Refactoring slot names for sub-classes of `CohortSize`

### ISSUE THREAD

**Issue by Puzzled-Face** [Roche/crmPack#573]
Splitting #407 into smaller packets (by class) to reduce the risk of conflicts.

```
> compare_slot_names("CohortSize")
# A tibble: 6 × 7
  Slot           CohortSizeRange CohortSizeDLT CohortSizeConst CohortSizeParts CohortSizeMax CohortSizeMin
  <chr>          <lgl>           <lgl>         <lgl>           <lgl>           <lgl>         <lgl>        
1 cohortSize     TRUE            TRUE          FALSE           FALSE           FALSE         FALSE        
2 cohortSizeList FALSE           FALSE         FALSE           FALSE           TRUE          TRUE         
3 DLTintervals   FALSE           TRUE          FALSE           FALSE           FALSE         FALSE        
4 intervals      TRUE            FALSE         FALSE           FALSE           FALSE         FALSE        
5 size           FALSE           FALSE         TRUE            FALSE           FALSE         FALSE        
6 sizes          FALSE           FALSE         FALSE           TRUE            FALSE         FALSE
```

I propose
- Renaming `cohortSize` to `cohort_size`
- `DLTintervals` to `intervals`

I am less certain about `cohortSizeList` and `sizes`.  

Options for `cohortSizeList` include
- Renaming to `cohort_size_list` to retain the distinction between the aggregate class and the atomic classes.
- Renaming to `cohort_size` for consistency with the atomic classes.

Options for `sizes` include
- Do nothing [I do not favour this option.]
- Rename to `size` for consistency with the atomic classes
- Rename to `cohort_size_list` or `cohort_size` (as appropriate) for consistency with the other aggregate classes

To do:

- [x] Revise documentation
	- [x] including adding the changes to the migration vignette
- [x] Amend all references to the slot in code in `/R`, `/examples` and `/vignettes`
- [x] Revise unit tests
- [x] Add entries to
   - [x] `NEWS.md`
   - [x]  `/vignettes/migration_from_the_old_crmPack.Rmd`
- [x] Rerun
  - [x] README.Rmd
  - [x] All vignettes
  - [x] All tests for all classes and functions
  - [x] All examples

**Comment by danielinteractive** [comment]
> Splitting #407 into smaller packets (by class) to reduce the risk of conflicts.

Sounds good. Also please no deprecation warnings as discussed to keep things simple, but instead can include the changes in the migration vignette.

> I propose
> 
> * Renaming `cohortSize` to `cohort_size`
> * `DLTintervals` to `intervals`

sounds good!
> 
> I am less certain about `cohortSizeList` and `sizes`.
> 
> Options for `cohortSizeList` include
> 
> * Renaming to `cohort_size_list` to retain the distinction between the aggregate class and the atomic classes.
> * Renaming to `cohort_size` for consistency with the atomic classes.

I would do `cohort_size_list` or `cohort_sizes` (plural)

> 
> Options for `sizes` include
> 
> * Do nothing [I do not favour this option.]
> * Rename to `size` for consistency with the atomic classes
> * Rename to `cohort_size_list` or `cohort_size` (as appropriate) for consistency with the other aggregate classes

Yes, can choose the same as above, so `cohort_size_list` or `cohort_sizes` (plural)
