### ISSUE TITLE
`approximate-Samples` generates plot output as a side-effect

### ISSUE THREAD

**Issue by Puzzled-Face** [Roche/crmPack#582]
The plot produced by `approximate` is generated as a side-effect (by `matplot`) when `verbose = TRUE`.  The plot is not part of the function's return value.  This seems sub-optimal (it is difficult for the end user to access the plot object) and makes unit testing more complicated than necessary.

Also, the online doc reads <html>
<body>

verbose | be verbose (progress statements and plot)? (default)
-- | --

</body>
</html>

which suggests that `verbose` is both misnamed and controls two options that should be independent (verbosity and production of the plot).

Suggestion:  
- modify `approximate`'s return value to be a list containing the approximated model and the plot (if requested) rather than just the approximated model
- modify `approximate` so that `verbose` controls only progress statements
- introduce a new parameter to control production of the plot. [`create_plot`, perhaps?]

**Comment by danielinteractive** [comment]
Sounds good, should be a small but useful change

**Comment by Puzzled-Face** [comment]
If the plot is requested, I suggest the list's elements should be named `model` and `plot`.  If the plot is not requested, should the return value be a list of length one with a single element named `model` or simply the model object itself?  The former is more internally consistent but creates a breaking change, the latter is a non-breaking change.

Given the scale of other changes that have already been made, I suggest it should be a single element list.

**Comment by danielinteractive** [comment]
Yeah single element list sounds good
