### ISSUE TITLE
Code in example.Rnw does not run correctly

### ISSUE THREAD

**Issue by Puzzled-Face** [Roche/crmPack#586]
in #581, `example.Rnw` compiles, but the code it contains produces incorrect results.  Currently, the first problem I've found is on page 99.

![image](https://github.com/Roche/crmPack/assets/133956382/bd10e30a-335e-49f0-874c-275e49237095)

Eight pages of purple warning messages then follow.  I think the problem is related to an incomplete renaming of parameters of `DualResponsesSamplesDesign` as part of the tidy-up.  Some calls use `Effmodel`, other `eff_model` but changing `Effmodel` to `eff_model` and vice versa cause errors to be thrown.

**Comment by danielinteractive** [comment]
Thanks @Puzzled-Face ! I will look at this today

**Comment by Puzzled-Face** [comment]
This appears to be a problem with line 3409 of `Design-methods.R`:

```
thisSigma2 <- mean(thisEffsamples@data$sigma2)
```

The `DataDual` class does not have a slot named `sigma2`.  I believe the correct reference is to `signa2W`.

Also changing references to `linewidth` to `size` to remove warnings in calls to various `ggplot2` functions.

**Comment by Puzzled-Face** [comment]
R CMD Check fails because it is unable to weave `crmPack-jss-paper.Rnw` successfully.  No error message is provided.  The file weaves successfully locally (albeit with `results=FALSE` rather than `results=hide`).

**Comment by Puzzled-Face** [comment]
Following the suggestion to convert the file using `Sweave2knitr("crmPack-jss-paper.Rnw")` leads to more errors:
```
Running pdflatex on crmPack-jss-paper-knitr.tex...failed

Issues: 41 errors, 36 warnings, 6 badboxes
```

Most, but not all of the errors, relate to missing citations.

**Comment by danielinteractive** [comment]
Hm ok. Let me check myself later tonight

**Comment by Puzzled-Face** [comment]
> R CMD Check fails because it is unable to weave `crmPack-jss-paper.Rnw` successfully. No error message is provided. The file weaves successfully locally (albeit with `results=FALSE` rather than `results=hide`).

Thanks to @cicdguy, this inconsistency was caused by _not_ having a full local TexLive installation.  In my case, this was resolved by

```
sudo apt-get update
sudo apt-get install -y texlive-full
```

The installation took some time.
