### ISSUE TITLE
An extension suggestion: IncrementsRelativeDLT.Cumulative.R

### ISSUE THREAD

**Issue by gunhanb** [Roche/crmPack#62]
This is an extension suggestion. A new class which is a slight modification of the existing IncrementsRelativeDLT class to take into account all DLTs so far (cumulative approach) instead of DLTs observed at the current dose. See the attached txt file for the R-code and documentation.

[IncrementsRelativeDLTCumulative.txt](https://github.com/Roche/crmPack/files/7735941/IncrementsRelativeDLTCumulative.txt)

**Comment by danielinteractive** [comment]
@gunhanb great, thanks! Let me know if you would like to chat about getting started on this together.

**Comment by gunhanb** [comment]
@danielinteractive Yes, certainly. I would like to chat about it.

**Comment by danielinteractive** [comment]
@gunhanb Hi Burak, anything I can help you here to make progress? thx!
