### ISSUE TITLE
Write a vignette for rolling CRM

### ISSUE THREAD

**Issue by dimitriskontosBAY** [Roche/crmPack#630]
**Summary**
- Later: write a vignette (in Rmd format?) for rolling CRM, to make it easier
  to start with this kind of design

**Comment by dimitriskontosBAY** [comment]
This seems to exist in vignette folder as rolling-crm.Rmd. Please check if this is indeed relevatn and if yes this issue can be removed.

**Comment by danielinteractive** [comment]
yes, done already
