### ISSUE TITLE
Create a class union for all `crmPack` classes

### ISSUE THREAD

**Issue by Puzzled-Face** [Roche/crmPack#652]
As suggested by @danielinteractive in the discussion of #649, it would be useful to introduce a [class union](https://stat.ethz.ch/R-manual/R-devel/library/methods/html/setClassUnion.html) that will allow us to identify a `crmPack` class in a single line of code and to use the class union in the definition of generics and methods that act on all `crmPack` classes (eg `tidy()`).

I suggest `CrmPackClass` as the name of the class union.  This could be declared either in `crmPack-package.R` or in a new file (`class-union.R`, perhaps?).  The package's collation order may need to be controlled by use of one or more `#' include` directives because "The classes in members must be defined before creating the union"...

**Comment by danielinteractive** [comment]
Thanks @Puzzled-Face , yeah separate file sounds good.
