### ISSUE TITLE
Meaning of the `step` argument to be clarified for `McmcOptions` class

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#73]
It wold be good to clarify the way we implement `step` feature. That is, if e.g. `step = 2` (without loss of generality, assume that `burnin = 0`, and `iteration = 6`), then a true sample to use would be `1, 3, 5`  or `2, 4, 6`. In other words, do we always start with the first one and then the next, every nth step? or we start from the step-th iteration? 

This question is to make `sample_size`, `save_sample` consistent.

**Comment by danielinteractive** [comment]
I think we should save samples `2,4,6` then. Generally, those samples where (sample - burnin) modulo step is 0.

**Comment by wwojciech** [comment]
Perfect. Thank you @danielinteractive So I will code our `McmcOptions` methods accordingly.
