### ISSUE TITLE
Question on roxygen aliases for methods

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#76]
Hi @danielinteractive!

I am wondering if we could consider not adding `-method` suffix for aliases of methods. For example, see `Model-methods.R` file and `@aliases dose-ModelTox-method` alias. I think this suffix does not anything more informative.

I think we use this for consistency with default aliases: e.g: ```\alias{dose,numeric,ModelTox,Samples-method}```

And actually, do you think we could get rid of these automatic aliases in favour of the one we specify manually with `@aliases`

What do you think Daniel?
Thanks a lot!

W.

**Comment by danielinteractive** [comment]
Hi @wwojciech yeah ok we can go without the '-manual' suffix for the aliases. There is no way to not have the automatic aliases, but they are not a problem for us so we don't need to worry about them.

**Comment by wwojciech** [comment]
Thank you Daniel! So I will use this Issue to create a PR for this change.

W.
