### ISSUE TITLE
`SafetyWindowConst` allows a vector of length > 1 for its `gap` slot

### ISSUE THREAD

**Issue by Puzzled-Face** [Roche/crmPack#817]
The online documentation for the `gap` slot of `SafetyWindowConst` as "a vector, the constant gap between patients".  But if  `gap` is a constant, why is a vector allowed?  The `follow` and `follow_min` slots, also constants, are of class `count`.  `gap` is of class `integer`.  Shouldn't this also be `count`?

One possible explanation is provided by the documentation of the `SafetyWindowSize` class.  This class allows the gaps between consecutive enrolments to vary depending on both the participant count and the cohort size.  Is the intention that `SafetyWindowConst` should also allow the gaps between consecutive enrolments to vary, but only based on participant count?  if so, the description of the `gap` slot should indicate that this is the case.

And, personally...
- If this is the case, I find the use of `Const` in the class name to be highly misleading.
- I find the documentation of both these classes to be very confusing.  For example the description of `SafetyWindowSize`  refers to a gap of 9 time units between the first and second patients, but `9` is not a value that appears in any of the slot values defined in the example.

## Recommendation
Either the code should be updated to match the descriptions, or the descriptions should be updated to match the code. 

Another possibility is that we need an extra class:
- `SafetyWindowConst` defines a constant safety window, regardless of participant count or cohort size
- [new class] `SafetyWindowPatientCount` defines a safety window that varies according to patient count
- `SafetyWindowSize` defines a safety window that varies according to both patient count and cohort size

Since `SafetyWindowSize` is the most generic class, this should be the superclass, with `SafetyWindowPatientCount` and `SafetywindowConst` being ever more specific subclasses.

**Comment by Puzzled-Face** [comment]
Ok.  From the example given in the documentation, it looks as if the definition of the `size` slot is wrong for `SafetyWindowSize`.  The definition of gap currently reads

a vector with the left bounds of the relevant cohort size intervals. This is used as follows. For instance, when we want to change the gap based on the cohort size, i.e. the time interval between the 1st and 2nd patient = 9 units of time and the rest time intervals are of 5 units of time when the cohort size is equal to or larger than 4. And the time interval between the 1st and 2nd patient = 7 units of time and the rest time intervals are 3 units of time when the cohort size is smaller than 4, then we specify `size = c(0L, 4L)`. This means, the right bound of the intervals are exclusive to the interval, and the last interval goes from the last value until infinity.

I think it should read:

a vector with the left bounds of the relevant cohort size intervals. This is used as follows. For instance, when we want to change the gap based on the cohort size, i.e. the time interval between the 1st and 2nd patient = 9 units of time and the rest time intervals are of 5 units of time when the cohort size is equal to or larger than 4. And the time interval between the 1st and 2nd patient = 7 units of time and the rest time intervals are 3 units of time when the cohort size is smaller than 4, then we specify **`gap = list(c(7, 3), c(9, 5))` and `size = c(0L, 4L)`**. This means, the right bound of the intervals are exclusive to the interval, and the last interval goes from the last value until infinity.

This also means that the `Const` in `SafetyWindowConst` refers to constancy *across* rather than *within* cohorts.

**Comment by danielinteractive** [comment]
OK thanks @Puzzled-Face , I will need some more time to look into this. Is this blocking anything else?

**Comment by Puzzled-Face** [comment]
> OK thanks @Puzzled-Face , I will need some more time to look into this. Is this blocking anything else?

No, it's not blocking anything else.  And I think the fix is simple: just update the documentation for `size` in `SafetyWindowSize`.  I'm more and more confident my latest interpretation is correct.
