### ISSUE TITLE
fix R CMD check problems

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#90]
To do:
- [x] notes for “no visible binding” can be ignored for now, same for missing imports - we will clean this up later
- [x] install vdiffr package
- [ ] some warning on size reduction for “crmPack-jss-paper.pdf” - will also clean up later
```
W  checking sizes of PDF files under ‘inst/doc’ (3s)
     ‘gs+qpdf’ made some significant size reductions:
        compacted ‘crmPack-jss-paper.pdf’ from 558Kb to 202Kb
     consider running tools::compactPDF(gs_quality = "ebook") on these files
```
- [x] undeclared vdiffr imports in tests - will do with Suggests
- [ ] RcppArmadillo
```
N  checking package dependencies (3.8s)
   Package suggested but not available for checking: ‘RcppArmadillo’
```

**Comment by wwojciech** [comment]
@danielinteractive I cleaned up the first bullet: “no visible binding” via PR #88.

**Comment by danielinteractive** [comment]
great, thx @wwojciech . If you can sneak in the other things in other PRs if it is only small changes then that is great. just tick them off here / close issue once all R CMD check problems gone. thx
