### ISSUE TITLE
add RNG related slots into `McmcOptions` class

### ISSUE THREAD

**Issue by wwojciech** [Roche/crmPack#91]
Add RNG related slots (kind, seed) into `McmcOptions` class.
The `kind` and `seed` slots should correspond to `.RNG.name` and `.RNG.seed` options available for `inits` parameter in `rjags::jags.model` function. Default values: `kind = "base::Mersenne-Twister"`, `seed = 1`.

**Comment by wwojciech** [comment]
@danielinteractive , I was also thinking a bit about it, and I think that it would be probably better if the default values for `kind` and `seed` are a kind of NULL, so that, if the use does not provide anything, we will not provide anything to `rjags`. Then, `rjags` will just some random `seed`. This approach will ensure that every time the `rjags` is run it will get different seed, which is similar as we have with base run funs like `rnorm`, etc. What do you think?

**Comment by danielinteractive** [comment]
@wwojciech thanks, yeah that is also ok. so you can change PR accordingly

**Comment by danielinteractive** [comment]
@wwojciech yeah but you could use `NA` from corresponding class, so e.g. `NA_real_` or so and then convert that to required thing inside `mcmc` function.

**Comment by wwojciech** [comment]
Yap, Thanks @danielinteractive, this seems to be the only, reasonable option when `NULL` cannot be used. I just though we can still use `NULL` slot, but it seems that we cannot :(.

**Comment by danielinteractive** [comment]
@wwojciech no worries, this is just a small detail - let's try to wrap this up soon :-)

**Comment by wwojciech** [comment]
@danielinteractive  Sure, it is ready now. Tx!
